### ISSUE TITLE
Wrong amount of contributions

### ISSUE THREAD

**Issue by felipecalvo** [sallar/github-contributions-chart#1] opened 2018-05-01 17:51 UTC
It's not working well with my profile. Says 0 contributions on 2015, but there are a few green squares.

![canvas](https://user-images.githubusercontent.com/11304439/39485412-0ada328a-4d4f-11e8-8c5d-f7ea8f865727.png)

Also we're barely scratching May on 2018 or am I missing something?

**Comment by sallar** [comment] 2018-05-01 18:25
@felipecalvo It's fixed now :) Please try again.

**Closed by sallar** 2018-05-01 18:25 UTC

**Comment by felipecalvo** [comment] 2018-05-01 18:30
That's great!

One more thing, I believe the 2018 graph is wrong. Those are the contributions of the last 365 days - it's the one that shows up on our profiles. If you look carefully you can see my 2017 contributions are duplicated on the first half-ish of 2018's.

**Comment by sallar** [comment] 2018-05-01 18:32
@felipecalvo yes you're right. I copied the way Github does it which apparently is not so correct... I'll try to give the user an option to change this.

**Comment by jfilter** [comment] 2018-05-01 19:45
yes, it's wrong for 2018. You can this also for my profile @jfilter.

**Comment by sallar** [comment] 2018-05-01 20:31
@jfilter @felipecalvo the issue is now fixed. current year won't go a full year back now
